# golangci-lint configuration for dtvem
# Documentation: https://golangci-lint.run/usage/configuration/

# Config version
version: 2

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files in linting
  tests: true

# Output configuration
output:
  # Colored output
  format: colored-line-number

  # Print lines of code with issue
  print-issued-lines: true

  # Print linter name in the end of issue text
  print-linter-name: true

  # Make issues output unique by line
  uniq-by-line: true

  # Sort results by: filepath, line and column
  sort-results: true

# Linters configuration
linters:
  # Disable all linters by default
  disable-all: true

  # Explicitly disable warning-only linters
  disable:
    - staticcheck  # Code improvement suggestions
    - revive       # Style suggestions
    - prealloc     # Performance hints
    - gosec        # Security false positives

  # Enable specific linters
  enable:
    # Bugs & Correctness (ERRORS - will fail build)
    - errcheck        # Check for unchecked errors
    - govet           # Reports suspicious constructs
    - ineffassign     # Detect ineffectual assignments
    - unused          # Check for unused constants, variables, functions and types

    # Style & Formatting (ERRORS - will fail build)
    - misspell        # Finds commonly misspelled English words in comments
    - whitespace      # Detect leading/trailing whitespace

    # Code Quality (ERRORS - will fail build)
    - dupl            # Detect code duplication
    - goconst         # Find repeated strings that could be constants
    - gocyclo         # Compute cyclomatic complexity

    # Best Practices (ERRORS - will fail build)
    - errorlint       # Find code that will cause problems with error wrapping
    - nilerr          # Find code that returns nil even if it checks that the error is not nil
    - nilnil          # Checks that there is no simultaneous return of nil error and invalid value

    # WARNINGS ONLY (disabled to prevent CI failure)
    # These are style/security suggestions that should not fail the build
    # Re-enable locally with: golangci-lint run --enable-all
    # - staticcheck     # Code improvement suggestions (QF quick-fixes)
    # - revive          # Style suggestions (comment formatting, etc.)
    # - prealloc        # Performance hints
    # - gosec           # Security warnings (often false positives)

linters-settings:
  # Settings for errcheck
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`
    check-type-assertions: true

    # Report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`
    check-blank: false

    # List of functions to exclude from checking
    exclude-functions:
      - (*os.File).Close
      - (*database/sql.Rows).Close

  # Settings for govet
  govet:
    # Enable all analyzers
    enable-all: true
    # Disable specific analyzers
    disable:
      - shadow  # Reports variables that shadow other variables (can be too noisy)

  # Settings for gocyclo (cyclomatic complexity)
  gocyclo:
    # Minimal code complexity to report
    min-complexity: 15

  # Settings for dupl (code duplication)
  dupl:
    # Threshold for duplicate code detection
    threshold: 100

  # Settings for goconst
  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimum occurrences count to trigger issue
    min-occurrences: 3
    # Ignore test files
    ignore-tests: true

  # Settings for misspell
  misspell:
    # Correct spellings using locale preferences
    locale: US

  # DISABLED LINTER SETTINGS (commented out since linters are disabled above)
  # Uncomment these when re-enabling the corresponding linters

  # # Settings for revive (replacement for golint)
  # revive:
  #   enable-all-rules: false
  #   rules:
  #     # ... (keep original rules for reference)

  # # Settings for gosec (security)
  # gosec:
  #   tests: true
  #   excludes:
  #     - G304  # File path provided as taint input

  # # Settings for staticcheck
  # staticcheck:
  #   checks: ["all"]

# Issues configuration
issues:
  # Which dirs to skip: issues from them won't be reported
  exclude-dirs:
    - vendor
    - dist
    - .claude

  # Which files to skip: issues from them won't be reported
  exclude-files:
    - ".*\\.pb\\.go$"  # Skip generated protobuf files

  # Exclude specific linters for matching issues
  exclude-rules:
    # Exclude known issues in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

    # Ignore long lines in comments (e.g., URLs)
    - linters:
        - revive
      text: "line is \\d+ characters"
      source: "^\\s*//.*https?://"

  # Maximum issues count per one linter
  # Set to 0 to disable limit
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  # Set to 0 to disable limit
  max-same-issues: 0

  # Show only new issues created after git revision
  # Useful for checking only your changes
  # new-from-rev: origin/main

  # Independently of option `exclude` we use default exclude patterns
  exclude-use-default: false
