name: Feature Request
description: Suggest a new feature or enhancement for dtvem
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your ideas for improving dtvem.

        **Note:** If you have a question or want to discuss ideas before submitting a formal feature request, please use [GitHub Discussions](https://github.com/dtvem/dtvem/discussions).

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe your proposed feature or enhancement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New runtime support (Ruby, Go, Rust, etc.)
        - Existing runtime enhancement
        - CLI command improvement
        - Installation/setup improvement
        - Configuration/settings
        - Performance improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Critical - I can't use dtvem without it
        - High - Would make dtvem much more useful
        - Medium - Nice to have
        - Low - Minor convenience
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature. Provide examples if possible.
      placeholder: |
        As a developer, I would...
        Example: dtvem install ruby 3.2.0
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: This would help users who...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/dtvem/dtvem/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
